title: Alauda Service Mesh
logoText: Alauda Service Mesh
lang: en
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml
releaseNotes:
  queryTemplates:
    fixed: |
      filter = 16502 AND Feature not in ("AIT - 平台打包") AND (resolution not in ("By Design", "Not a Bug", Duplicate, Rejected, "Cannot Reproduce") OR resolution is EMPTY) AND (ACPFixVersions in (v4.0.0) or fixVersion in versionMatch(v4.0.0)) AND status in (Done, Resolved, 已完成) AND (affectedVersion in versionMatch("3.1[0-8]") OR ((issueFunction in linkedIssuesOf("affectedVersion in versionMatch('3.1[0-8]')", clones) OR issueFunction in linkedIssuesOf("affectedVersion in versionMatch('3.1[0-8]')", "is cloned by")))) and ReleaseNotesStatus = Publish  and project = ASM  AND component not in (ML-GPU调度器, ML-GPU适配, ML-物理GPU, ML-虚拟GPU)  
    unfixed: |
      filter = 18959 AND ACPAffectVersions in (v4.0.0) AND NOT (ACPFixVersions in (v4.0.0) AND status in (Done, Resolved)) AND (labels not in (安全问题) OR labels is EMPTY) and ReleaseNotesStatus = Publish and project = ASM AND component not in (ML-GPU调度器, ML-GPU适配, ML-物理GPU, ML-虚拟GPU)
